excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://krishnanand-singh.github.io
title: Krishnanand Singh
tagline: A Journal of the Things I do and Stuff I like to do
description: Whatever came to my mind
paginate: 1