excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://krishnanand-singh.github.io
title: KN
tagline: Diary of an introvert geek
description: A Journal of the Things I do and Stuff I like to do
paginate: 1
